project_id = "hnxwfxgibkkxonziuzed"

[functions.xaveco]
verify_jwt = false

[functions.upgrade]
verify_jwt = false

[functions.check]
verify_jwt = false

[functions.start-trial]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
